#!/bin/bash

set -e

restore_configs

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/skr_pro
$CFGDIR/accessories/dummy-extruder
$CFGDIR/accessories/tmc2209
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/dual-drivers-on-xy

export PLATFORMIO_ENV=BIGTREE_SKR_PRO
