inputs:
  branch:
    description: "Marlin branch or tag"
    default: "bugfix-2.0.x"
  machine:
    description: "Machine code"
    default: "V1CNC_Rambo"

runs:
  using: "composite"
  steps:
    # Based on .github/workflows/test-builds.yml
    - name: Select Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio-core/archive/master.zip
        platformio update

    - name: Check out MarlinBuilder
      uses: actions/checkout@v2

    - name: Check out MarlinFirmware
      uses: actions/checkout@v2
      with:
        repository: MarlinFirmware/Marlin
        ref: ${{ inputs.branch }}
        path: Marlin
        clean: true
        fetch-depth: 1

    - name: Configure
      run: |
        src/core/config-for-machine ${{ inputs.machine }}
