#!/bin/bash

## Script Setup

set -ex
. $(dirname "$0")/core/env

## Parse arguments for machine
export CONFIG_NAME=$1
shift
# Exit if we don't have a CONFIG_NAME name
[ "$CONFIG_NAME" ] || exit 2

## Move to Marlin Dir
cd "$V1_ROOT/$MARLINDIR"

## Set up configs
export PATH=$PATH:buildroot/bin

restore_configs

echo "# ${CONFIG_NAME} - ${MARLIN_VERSION} - ${V1_VERSION}" > README.md
. $CFGDIR/$CONFIG_NAME

## Build
platformio run --project-dir . -e "$PLATFORMIO_ENV" --silent "$@"

# Copy the output file out here, so we can save it as an artifact
cp .pio/build/$PLATFORMIO_ENV/firmware.[bh]* ../
