#!/bin/bash

## Script Setup

set -ex
. $(dirname "$0")/env

## Parse arguments for machine
machine=$1
shift
# Exit if we don't have a machine name
[ "$machine" ] || exit 2

## Move to Marlin Dir
cd "$V1_ROOT/$MARLINDIR"

## Set up configs
export PATH=$PATH:buildroot/bin

restore_configs

. $CFGDIR/$machine

## Build
platformio run --project-dir . -e "$PLATFORMIO_ENV" --silent "$@"

# Copy the output file out here, so we can save it as an artifact
cp .pio/build/$PLATFORMIO_ENV/firmware.[bh]* ../

