#!/bin/bash

set -ex
. $(dirname "$0")/core/version
. $(dirname "$0")/core/env

## Move to Marlin Dir
cd "$V1_ROOT/$MARLINDIR"

# Since we will be zipping up this folder as an artifact, let's clean it up a bit first.
rm -rf \
    .git \
    .gitattributes \
    .github \
    .gitignore \
    .pio \
    process-palette.json \
    buildroot \
    config \
    data \
    docs \
    lib \

