name: rambo

on:
  push:

  pull_request:
    branches:
    - main
    paths-ignore:
    - src/configs/V1*Archim*
    - src/configs/V1*Ramps*
    - src/configs/V1*Skr*
    - '**/*.md'
  release:
    types:
      - published

jobs:
  build:

    env:
      MARLIN_VERSION: ${{ matrix.branch }}
      CONFIG_NAME: ${{ matrix.machine }}

    name: ${{ matrix.machine }}-${{ matrix.branch }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # Allow all machines to finish building
      matrix:
        branch:
        - 2.0.6
        machine:
        - V1CNC_Rambo

    steps:

    # First, cancel unfinished jobs.
    - uses: technote-space/auto-cancel-redundant-job@v1

    - name: prebuild
      uses: ./.github/actions/prebuild
      with:
        branch: ${{ matrix.branch }}
        machine: ${{ matrix.machine }}

    - name: platformio
      uses: ./.github/actions/platformio

    - name: Build
      uses: ArminJo/arduino-test-compile@v2
      with:
        sketch-names: Marlin.ino
        # -fqbn in the first line of the arduino console log.
        arduino-platform: arduino:avr,rambo:avr
        arduino-board-fqbn: rambo:avr:rambo
        # This is what you would put into the board manager url.
        platform-url: https://raw.githubusercontent.com/ultimachine/ArduinoAddons/master/package_ultimachine_index.json
        # Save the .hex/.bin/whatever file. It should end up in $HOME/Marlin/
        set-build-path: true
        required-libraries: U8glib

    - name: Zip up Marlin
      run: |
        src/core/zip-marlin

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.machine }}-${{ matrix.branch }}
        path: |
          firmware_*
          Marlin*.zip
