name: rambo

on:
  schedule:
    # At 12:15 each day. No idea what time zone this is...
    - cron:  '15 12 * * *'
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    paths-ignore:
    - src/configs/V1*Archim*
    - src/configs/V1*Ramps*
    - src/configs/V1*Skr*
    - '**/*.md'

jobs:
  build:

    env:
      MARLIN_VERSION: ${{ matrix.branch }}
      CONFIG_NAME: ${{ matrix.machine }}

    name: ${{ matrix.machine }}-${{ matrix.branch }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # Allow all machines to finish building
      matrix:
        branch:
        - 2.0.6
        machine:
        - V1CNC_Rambo

    steps:
    - name: Dump GitHub.event context
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event) }}
      run: echo "$GITHUB_CONTEXT"
